homework_2
Puvel/courses-app pull request #2
Opened 2023-03-24 10:49 UTC by Puvel

2023-03-24 11:59 UTC, KitTheProgrammer requested changes
1. I think this error should be present only on the registration page
![image](https://user-images.githubusercontent.com/44047007/227514466-207113fd-5ed0-4444-a3e1-6bbdc7c007e4.png)
2. Writing some random number as course id causes the app to crash (like this: /courses/12345)
![image](https://user-images.githubusercontent.com/44047007/227514927-96894f84-906f-4dfc-a8a9-c1a0cb6c4414.png)
3. You can create authors with name containing only spaces 
![image](https://user-images.githubusercontent.com/44047007/227515059-51ec5760-e7af-490d-8467-e50da57a838f.png)
4. If you create a new course and then try to go to it's route app is crashing (by writing course/<new course id>. After reload newly created course is disappearing

2023-03-24 11:59 UTC, KitTheProgrammer commented on src/App.jsx
> +	);
It is better to set the initial value from `useEffect`

You have one already at line 45, you can do it there

2023-03-24 11:59 UTC, KitTheProgrammer commented on src/components/CourseInfo/CourseInfo.jsx
> +	const course = courses.find((course) => course.id === courseId);
Use `useMemo` here

2023-03-24 11:59 UTC, KitTheProgrammer commented on src/components/Login/Login.jsx
> +		inputsStates[ukey](value);
I understand the idea, but it feels too redundant here. You have only 2 fields, that can be set like this:
`<input onChange={({ target: { value } }) => setPassword(value)}`

2023-03-24 11:59 UTC, KitTheProgrammer commented on src/components/Registration/Registration.jsx
> +
same here

2023-03-24 11:59 UTC, KitTheProgrammer commented on src/components/Registration/Registration.jsx
> +					onClick={() => setShowPass((prevState) => !prevState)}
usage of prev state is unnecessary

2023-03-28 15:52 UTC, EpamFanAnton approved these changes
25

2023-04-03 20:21 UTC, merged